### ISSUE TITLE
fair use of hosted instance?

### ISSUE THREAD

**Issue by Entkenntnis** [Knorrke/socialbotnet#70]
Hey! Found this project recently and gave it a try today ^^ so ... it's basically about botting, so I tried some like-farming, which is kinda slow as you have to register a lot of bots.

[My script](https://gist.github.com/Entkenntnis/46f850a3306ba70ebff24b01274ede48) was probably a bit aggressive, so it maxed out the server and the hosted instance is in maintainance mode now. Which leads me to the question: What are the fair use limits of the hosted instance?

I think the topic is a bit complicated, as the fun part is actually writing a bot and farm likes, which this is putting a lot of stress on the server (with almost no client resources used) - and I really wanted to get 100.000 likes!

But it seems this is not really a sustainable way of using the hosted instance, so I stopped my script.

(some crazy idea, maybe limit the maximum amount of likes to 1000? it's just so annoying to see somebody having more likes than me, hehe xD)

**Comment by Knorrke** [comment]
Hey, thanks for reaching out. I'm currently looking into the db, trying to figure out why it got so slow. Server should be fast enough, the static pages load normally, but there seems to be an issue when the user table gets big. I'll bring it back online tomorrow, once I figured this out.

>maybe limit the maximum amount of likes to 1000? it's just so annoying to see somebody having more likes than me, hehe xD

Yeah, I thought about that too. It got a bit out of hand lately^^ Though, you did get into trending#1 ;) 

As for your question about fair use limits: There currently aren't any, since when the server got slow it sofar was always due to a slow db query somewhere. I was able to fix these issues usually. I think it generally is the appeal of the project to not be restricted in what you program the bot for. But a cap on the likes makes sense, I'll definitely think about it. Currently the amount of users is the bigger issue though and that is harder to restrict.

**Comment by Knorrke** [comment]
Ok, so, it is not connected to a slow db query this time but the overall db connection gets too busy on this load level. Not sure how to speed that up actually... I put the app back up for now. Feel free to run your script, if the response time isn't an issue for you.

**Comment by Entkenntnis** [comment]
Can confirm that the bottleneck was the redirect to the landing page - requesting the main page is slow (~800ms for me) and the previous version of the script was following the redirect after each registration.

With this change, the script now runs fine - server response time increased to 3-5 seconds, but no time-outs. I can sustain a bot creation rate of 10 bots/sec

**Comment by Entkenntnis** [comment]
Have you changed something? Server speed increased by 25% to 12.5 bots/sec :)

**Comment by Knorrke** [comment]
Not right now, no. Last deploy was yesterday with #71. The hosted server is running on a VPS though, maybe they have some performance fluctuation?
